/**
 *
 * $Id$
 */
package subkdm.SimplifiedDecisionMetrics.validation;

import org.eclipse.emf.common.util.EList;

import subkdm.SimplifiedDecisionMetrics.Measurement;

import subkdm.kdmObjects.ModelElement;

/**
 * A sample validator interface for {@link subkdm.SimplifiedDecisionMetrics.MofElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MofElementValidator {
	boolean validate();

	boolean validateMeasurant(EList<Measurement> value);
	boolean validateElement(ModelElement value);
}
