/**
 *
 * $Id$
 */
package subkdm.kdmRelations.validation;

import subkdm.kdmObjects.AbstractCodeElement;

/**
 * A sample validator interface for {@link subkdm.kdmRelations.AbstractCodeRelationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractCodeRelationshipValidator {
	boolean validate();

	boolean validateTo(AbstractCodeElement value);
	boolean validateFrom(AbstractCodeElement value);
}
