/**
 *
 * $Id$
 */
package subkdm.SimplifiedDecisionMetrics.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import subkdm.SimplifiedDecisionMetrics.Measure;

/**
 * A sample validator interface for {@link subkdm.SimplifiedDecisionMetrics.Observation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ObservationValidator {
	boolean validate();

	boolean validateWhenObserved(Date value);
	boolean validateMeasures(EList<Measure> value);
}
