/**
 *
 * $Id$
 */
package subkdm.kdmObjects.validation;

import org.eclipse.emf.common.util.EList;

import subkdm.kdmObjects.CommentUnit;

import subkdm.kdmRelations.AbstractCodeRelationship;

/**
 * A sample validator interface for {@link subkdm.kdmObjects.AbstractCodeElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractCodeElementValidator {
	boolean validate();

	boolean validateCodeRelation(EList<AbstractCodeRelationship> value);
	boolean validateComment(EList<CommentUnit> value);
	boolean validateName(String value);
}
